name: Testing App with RemoteSwingLibrary

on: [push, pull_request]

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: x11vnc/docker-desktop
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Run tests on Linux
        if: runner.os == 'Linux'
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo pwd: $PWD
          # echo workspace: $(ls ${{ github.workspace }})

          sudo apt update -y

          sudo apt-get install unzip






          # timestamp=timeStampFolder$(date +%s)
          # mkdir $timestamp
          # cd $timestamp
          echo "Performing veraPDF installation ... "

          echo "#Downloading veraPDF, latest dev version ... unziping to $PWD" 
          curl -LO https://software.verapdf.org/dev/verapdf-installer.zip
          unzip verapdf-installer.zip

          #Definition of the variable, pointing to the veraPDF directory with installation files
          veradir=$(ls | grep verapdf-greenfield)
          cd "$veradir"

          #Definition of the Env variable
          export veraPATH="./verapdf"
          echo "veraPATH: $veraPATH" 

          curl -LO  https://raw.githubusercontent.com/veraPDF/veraPDF-regression-tests/integration/tools/auto-install.xml

          #Definition of the 'PATH' to install veraPDF using the auto-install.xml file
          sed -i '5 c\        <installpath>'$(echo $veraPATH)'</installpath>' ./auto-install.xml

          echo $(cat auto-install.xml)

          veraizpack=$(ls | grep verapdf-izpack-installer)
          echo "veraizpack: $veraizpack"

          #Performing installation
          echo "Performing installation veraPDF ... "
          java -jar "$veraizpack" auto-install.xml

          #Checking version
          currentIFS=$IFS 
          IFS='-'
          read -r -a array <<< "$veradir"
          VERSION="${array[2]}"
          IFS=$currentIFS

          echo "veraPDF version: $VERSION"
          echo "veraPATH: $veraPATH   $PWD" 
          echo ls PWD: $(ls $PWD)
          # cd verapdf
          echo verapdf dir: $(ls $PWD/verapdf)
          # echo ls PWD: $(ls -la $PWD)
          ./verapdf/verapdf --version

          java -version
          javac -version
          whoami 

          # sudo apt-get install x11-apps

          export DISPLAY=:0.0
          ./verapdf/verapdf-gui 

          # echo "Running regression-tests ..."
          # PATH="./bats:./bats/bin:$PATH"
          # echo "$PATH"
          # echo "PWD: "$PWD
          # echo list: $(ls ./)
          # echo workspace: $(ls ${{ github.workspace }})

          # ${{ matrix.set_display }}
          # mvn clean verify -Dexcludes=Webstart

      # - name: Robot Framework
      #   uses: tarathep/robotframework-github-action@v1.0
