name: Testing App with RemoteSwingLibrary

on: [push, pull_request]

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: x11vnc/docker-desktop
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
      
      
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

      - name: Set up Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      # - name: Set up Python 3.10
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: 3.10

      - name: Run tests on Linux
        if: runner.os == 'Linux'
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo pwd: $PWD
          cd /home
          echo pwd: $PWD
          # echo workspace: $(ls ${{ github.workspace }})

          sudo apt update -y
          sudo apt install xvfb -y

          sudo apt install python3 -y
          sudo apt install -y python3-pip
          sudo pip install robotframework

          sudo apt-get install unzip

          echo "Performing veraPDF installation ... "

          echo "#Downloading veraPDF, latest dev version ... unziping to $PWD" 
          curl -LO https://software.verapdf.org/dev/verapdf-installer.zip
          unzip verapdf-installer.zip

          #Definition of the variable, pointing to the veraPDF directory with installation files
          veradir=$(ls | grep verapdf-greenfield)
          cd "$veradir"

          #Definition of the Env variable
          export veraPATH="/home/verapdf"
          echo "veraPATH: $veraPATH" 

          curl -LO  https://raw.githubusercontent.com/veraPDF/veraPDF-regression-tests/integration/tools/auto-install.xml

          #Definition of the 'PATH' to install veraPDF using the auto-install.xml file
          sed -i '5 c\        <installpath>'$(echo $veraPATH)'</installpath>' ./auto-install.xml

          echo $(cat auto-install.xml)

          veraizpack=$(ls | grep verapdf-izpack-installer)
          echo "veraizpack: $veraizpack"

          #Performing installation
          echo "Performing installation veraPDF ... "
          java -jar "$veraizpack" auto-install.xml

          echo verapdf dir: $(ls /home/verapdf)
          /home/verapdf/verapdf --version

          java -version
          javac -version
          python3 --version
          python3 -m pip list
          whoami 

          # sudo apt-get install x11-apps

          # export DISPLAY=:0.0
          # export DISPLAY=:99.0
# https://github.com/hajimehoshi/ebiten/issues/939
      # - name: Test
      #   env:
      #     DISPLAY: ":99.0"
      #   run: |
      #     xvfb-run --auto-servernum  go test -race -v ./...

      
      - name: Running verapdf-gui 
        run: |
          # export DISPLAY=:99
          # sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

          # sudo apt install xvfb -y
          # sudo yum install Xvfb -y

          export DISPLAY=:99; Xvfb :99 -screen 0 1024x768x16 -ac -noreset & sleep 3
          echo "Running gui ..."
          /home/verapdf/verapdf-gui &
          ps aux       


          java -jar /home/verapdf/bin/greenfield-apps-1.23.147.jar &
          ps aux

          echo "Running regression-tests ..."
          echo PATH: "$PATH"

          # ${{ matrix.set_display }}
          # mvn clean verify -Dexcludes=Webstart

          echo "cd to: /__w/remoteswinglibrary/remoteswinglibrary/"

          cd /__w/remoteswinglibrary/remoteswinglibrary/

          echo pwd: $PWD
          echo running curl ...
          curl -LO https://repo1.maven.org/maven2/org/robotframework/remoteswinglibrary/2.3.1/remoteswinglibrary-2.3.1.jar
          echo setting classpath
          sudo export CLASSPATH=.;./remoteswinglibrary-2.3.1.jar;
          echo %CLASSPATH%
          echo dir: $(ls ./)

          # robot --version
          robot /__w/remoteswinglibrary/remoteswinglibrary/
      # - name: Robot Framework
      #   uses: tarathep/robotframework-github-action@v1.0
