name: Testing veraPDF GUI with RemoteSwingLibrary and Robot Framework
on: [push, pull_request]

jobs:
  veraPDF-GUI-check:
    runs-on: ubuntu-latest
    container:
      image: x11vnc/docker-desktop
    strategy:
      matrix:
        java: [ '8', '11' ]
    name: Running on Java ${{ matrix.Java }} 

    steps:
      - uses: actions/checkout@v3
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

      - name: Set up Java              # See 'Supported distributions': https://github.com/actions/setup-java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Preparing Linux packages(veraPDf, Python, xvfb, unzip)
        if: runner.os == 'Linux'
        run: |
          echo pwd: $PWD
          echo dir: $(ls ./)
          cd /home
          echo pwd: $PWD

          sudo apt update -y

          sudo apt install xvfb -y
          sudo apt install python3 -y
          sudo apt install -y python3-pip
          sudo pip install robotframework
          sudo apt-get install unzip

          echo "Performing veraPDF installation ... "
          echo "#Downloading veraPDF, latest dev version ... unziping to $PWD" 
          curl -LO https://software.verapdf.org/dev/verapdf-installer.zip
          unzip verapdf-installer.zip

          #Definition of the variable, pointing to the veraPDF directory with installation files
          veradir=$(ls | grep verapdf-greenfield)
          cd "$veradir"

          #Definition of the Env variable
          export veraPATH="/home/verapdf"
          echo "veraPATH: $veraPATH" 

          echo "#Downloading auto-install.xml ..." 
          curl -LO  https://raw.githubusercontent.com/veraPDF/veraPDF-regression-tests/integration/tools/auto-install.xml

          #Definition of the 'PATH' to install veraPDF using the auto-install.xml file
          sed -i '5 c\        <installpath>'$(echo $veraPATH)'</installpath>' ./auto-install.xml
          echo $(cat auto-install.xml)

          veraizpack=$(ls | grep verapdf-izpack-installer)
          echo "veraizpack: $veraizpack"

          echo "Performing installation veraPDF ... "
          java -jar "$veraizpack" auto-install.xml

          echo verapdf dir: $(ls /home/verapdf)
          /home/verapdf/verapdf --version

          java -version
          javac -version
          python3 --version
          python3 -m pip list
          whoami 

      - name: Running verapdf-gui
        run: |
          export DISPLAY=:99; Xvfb :99 -screen 0 1024x768x16 -ac -noreset & sleep 3

          echo "Running gui ..."
          /home/verapdf/verapdf-gui &
          ps aux       

          echo PATH: "$PATH"
          echo "cd to: /__w/remoteswinglibrary/remoteswinglibrary/"
          cd /__w/remoteswinglibrary/remoteswinglibrary/

          echo pwd: $PWD
          echo "running curl to get remoteswinglibrary-2.3.1.jar ..."
          curl -LO https://repo1.maven.org/maven2/org/robotframework/remoteswinglibrary/2.3.1/remoteswinglibrary-2.3.1.jar
          
          echo "setting PYTHONPATH"
          export CLASSPATH=$CLASSPATH:./remoteswinglibrary-2.3.1.jar
          export PYTHONPATH=${PYTHONPATH}:./:/__w/remoteswinglibrary/remoteswinglibrary/remoteswinglibrary-2.3.1.jar
          export
                    
          mkdir Results
          echo dir: $(ls ./)

          echo "Running regression-tests ..."
          export ROBOT_OPTIONS="--outputdir Results"
          robot  ./tests/*.robot

      - name: Generating report
        uses: actions/upload-artifact@v1
        if: success() || failure()
        with:
          name: Results
          path: "./Results"
